# Generated by Django 4.0.5 on 2022-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_preferredproducts_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사용자 계정'),
        ),
    ]
