# Generated by Django 4.0.5 on 2022-06-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='ghost', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
